trigger:
  batch: 'true'
  branches:
    include:
    - main
  paths:
    include:
      - MicroServices/*
      - azure-pipelines-discord-gamemanager.yml

resources:
- repo: self

stages:
- stage: Build_GameManager_Image
  displayName: Build GameManager Image
  jobs:
  - job: Build_GameManager_Image
    displayName: Build GameManager Image
    pool:
      name: Redshift-OnPrem-Linux
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build GameManager Image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHub-awesomejack295'
        repository: 'awesomejack295/viperaveilgamemanager'
        dockerfile: './MicroServices/GameManager/Dockerfile'
        tags: latest
    - task: CmdLine@2
      displayName: Cleaning up images older than 24H
      inputs:
       script: 'docker system prune -a --force --filter "until=24h"' 

    - task: CmdLine@2
      displayName: Cleaning up unneeded images
      inputs:
       script: 'docker system prune -f'