trigger:
  batch: 'true'
  branches:
    include:
    - main
  paths:
    include:
      - Discord-ELO/*
      - azure-pipelines-discord-elo.yml

resources:
- repo: self

stages:
- stage: Build_ViperaVeilELO_Image
  displayName: Build ViperaVeil-ELO image
  jobs:
  - job: Build_ViperaVeilELO_Image
    displayName: Build ViperaVeil-ELO image
    pool:
      name: Redshift-OnPrem-Linux
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Building ViperaVeil-ELO Image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHub-awesomejack295'
        repository: 'awesomejack295/viperaveilelo'
        dockerfile: './Discord-ELO/Dockerfile'
        tags: latest
    - task: CmdLine@2
      displayName: Cleaning up images older than 24H
      inputs:
       script: 'docker system prune -a --force --filter "until=24h"' 

    - task: CmdLine@2
      displayName: Cleaning up unneeded images
      inputs:
       script: 'docker system prune -f'