apiVersion: v1
kind: Service
metadata:
  name: postgres-viperaveil
  namespace: postgres
  labels:
    app: postgres-viperaveil
spec:
  ports:
  - name: tcp5434
    port: 5434
    protocol: TCP
    targetPort: 5432
  externalIPs:
    - 10.40.0.80
  selector:
    app: postgres-viperaveil
  sessionAffinity: None
  type: ClusterIP