kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: postgres
  name: viperaveil-data-longhorn
  labels:
    app: postgres-viperaveil
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi