apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: mediacms/mediacms:latest
        volumeMounts:
        - name: app-volume
          mountPath: /home/mediacms.io/mediacms/
        env:
        - name: ENABLE_UWSGI
          value: "no"
        - name: ENABLE_NGINX
          value: "no"
        - name: ENABLE_CELERY_BEAT
          value: "no"
        - name: ENABLE_MIGRATIONS
          value: "no"
      volumes:
      - name: app-volume
        hostPath:
          path: /path/to/your/local/directory
