apiVersion: v1
kind: Pod
metadata:
  name: migrations
spec:
  containers:
  - name: migrations
    image: mediacms/mediacms:latest
    volumeMounts:
    - name: app-volume
      mountPath: /home/mediacms.io/mediacms/
    env:
    - name: ENABLE_UWSGI
      value: "no"
    - name: ENABLE_NGINX
      value: "no"
    - name: ENABLE_CELERY_SHORT
      value: "no"
    - name: ENABLE_CELERY_LONG
      value: "no"
    - name: ENABLE_CELERY_BEAT
      value: "no"
    - name: ADMIN_USER
      value: "admin"
    - name: ADMIN_EMAIL
      value: "admin@localhost"
    # Uncomment and set the ADMIN_PASSWORD environment variable if needed
    # - name: ADMIN_PASSWORD
    #   value: "your_password_here"
    command: ["./deploy/docker/prestart.sh"]
    restartPolicy: OnFailure
    readinessProbe:
      exec:
        command:
        - pg_isready
        - -U
        - mediacms
      initialDelaySeconds: 10
      periodSeconds: 10
  volumes:
  - name: app-volume
    hostPath:
      path: /path/to/your/local/directory
