apiVersion: apps/v1
kind: Deployment
metadata:
  name: viperaveilapi
  namespace: viperaveil
spec:
  selector:
    matchLabels:
      app: viperaveilapi
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: viperaveilapi
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: 'awesomejack295/viperaveilapi'
        name: viperaveilapi
        imagePullPolicy: Always
        ports:
         - containerPort: 5000
           name: tcp5000
           protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
      imagePullSecrets:
       - name: dockersecret
      restartPolicy: Always