apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-viperaveilapi-config
  namespace: postgres
  labels:
    app: postgres-viperaveilapi
data:
  POSTGRES_DB: postgres-viperaveilapi
  POSTGRES_USER: postgres-viperaveilapi
  POSTGRES_PASSWORD: 7xwlf2r08mhz
  PGDATA: /var/lib/postgresql/data/postgres-viperaveilapi