apiVersion: v1
kind: Service
metadata:
  name: postgres-viperaveilapi
  namespace: postgres
  labels:
    app: postgres-viperaveilapi
spec:
  ports:
  - name: tcp5435
    port: 5435
    protocol: TCP
    targetPort: 5432
  externalIPs:
    - 10.40.0.80
  selector:
    app: postgres-viperaveilapi
  sessionAffinity: None
  type: ClusterIP