apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-viperaveilapi
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres-viperaveilapi
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-viperaveilapi
    spec:
      containers:
        - name: postgres-viperaveilapi
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          image: postgres:12
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-viperaveilapi-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: viperaveilapi-data-longhorn